### ISSUE TITLE
Key 'mpms' is not in struct

### ISSUE THREAD

**Issue by bartoszptak** [asanomitakanori/mfa-feature-warping#8]
The repository is full of bugs and missing code. It is hard to reproduce results.

```
Traceback (most recent call last):
  File "/home/host/Projects/mfa-feature-warping/train.py", line 171, in main
    train_net(net=net, device=device, cfg=cfg, val_clip=val_clip)
  File "/home/host/Projects/mfa-feature-warping/train.py", line 28, in train_net
    train = Heatmap_Dataset(cfg.train, cfg.dataloader)
  File "/home/host/Projects/mfa-feature-warping/utils/dataset_train.py", line 16, in __init__
    self.gts_dir = abs_path(cfg_type.mpms)
omegaconf.errors.ConfigAttributeError: Key 'mpms' is not in struct
    full_key: train.mpms
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by kaneki-11** [comment]
Has the problem been solved？

**Comment by bartoszptak** [comment]
No
